############################################
# DEV Configuration
############################################

management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=false
management.metrics.enable.jvm=true